<?php

namespace AdminBundle\Repository;

/**
 * ContentBlockRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ContentBlockRepositoryEn extends \Doctrine\ORM\EntityRepository
{
}
