<?php

namespace AdminBundle\Repository;

/**
 * ContentBlockImageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ContentBlockImageRepositoryEn extends \Doctrine\ORM\EntityRepository
{
}
