<?php

namespace Angleto\BookingBundle\Repository;

/**
 * HotelRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HotelRepositoryUa extends \Doctrine\ORM\EntityRepository
{
}
