<?php

namespace Angleto\BookingBundle\Repository;

/**
 * OptionsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OptionsRepositoryUa extends \Doctrine\ORM\EntityRepository
{
}
