<?php

namespace Angleto\BookingBundle\Repository;

/**
 * RoomRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RoomRepositoryEn extends \Doctrine\ORM\EntityRepository
{
}
