<?php

namespace Angleto\BookingBundle\Repository;

/**
 * RoomGalleryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RoomGalleryRepository extends \Doctrine\ORM\EntityRepository
{
}
